### ISSUE TITLE
AbstractRestBetaResource::post()

### ISSUE THREAD

**Issue by nataniel** [ircykk/allegro-api#1]
Warning: Declaration of Ircykk\AllegroApi\Rest\AbstractRestBetaResource::post($path, array $params = Array, array $requestHeaders = Array) should be compatible with
Ircykk\AllegroApi\Rest\AbstractRestResource::post($path, $data, array $requestHeaders = Array) in /home/rebel/admin/vendor/ircykk/allegro-api/src/Rest/AbstractRestBetaResource.php on line 60

**Comment by ircykk** [comment]
Thx for report, fixed e473d32fec625ccf261d09bab7d509b96df9f2f8
