### ISSUE TITLE
Timeout połączenia z REST

### ISSUE THREAD

**Issue by juhacz** [ircykk/allegro-api#6]
Czy da się jakoś ustawić timeout dla połączeń REST? Opiszę swój problem.
Mam skrypt, który pobiera przez get /offers/listing wszystkie aukcje z danej kategorii. W większości to działa, ale czasami się zdarza, że uruchomiony skrypt nie może z niewiadomych mi powodów połączyć się z Allegro i program się kończy po 60 sekundach zwracając błąd.
Owy skrypt uruchamiam na serwerze z innego skryptu nadrzędnego co pewien czas jako CGI. 
Skrypt nadrzędny kończy się, podrzędny, czyli ten o którym mowa, ma problem z połączeniem i w ten sposób zostaje jako proces zombie na serwerze. Po kilku godzinach mam kilkadziesiąt takich procesów zombi i nie wiem jak sobie z tym poradzić.
Czy da się jakoś ustawić timeout dla połączeń REST, tak bay np. po 10 s. niemożności połączenia się dłużej nie próbował? SOAP od wielu lat działa bez problemu, ale z REST są jakieś przeboje, nie wiem jak sobie z tym poradzić. Dzięki za wskazówki.

**Comment by ircykk** [comment]
Na szybko, trzeba przekazać HttpClient'a  z własną konfiguracją, ustawić timeout http://docs.guzzlephp.org/en/stable/request-options.html#connect-timeout i z takiego klienta korzystać. Później postaram się napisać dokładniej.

**Comment by juhacz** [comment]
Dzięki, to czekam na podpowiedź, bo sam jestem chyba za cienki :)

**Comment by ircykk** [comment]
Do klienta wrzucasz ClientBuilder'a (przez adapter) z własną konfiguracją, np. guzzle:

```php
$clientBuilder = new \Ircykk\AllegroApi\HttpClient\HttpClientBuilder(
    new Http\Adapter\Guzzle6\Client(
        new \GuzzleHttp\Client([
            'timeout' => 1,
            'connect_timeout' => 1,
        ])
    )
);

$client = new Client($credentials, $clientBuilder);

// $response = $client->sale()->categories()->all();
```

Parametry jak w [doc guzzle](http://docs.guzzlephp.org/en/stable/quickstart.html), po przekroczeniu czasu powinieneś dostać exception:

`Fatal error: Uncaught GuzzleHttp\Exception\ConnectException: cURL error 28: Operation timed out after 1000 milliseconds with 0 out of 0 bytes received`
