### ISSUE TITLE
GET sale/offer-events

### ISSUE THREAD

**Issue by juhacz** [ircykk/allegro-api#7]
Hej

Straciłem dzisiaj dobre kilka godzin i nie udało mi się dobić do zasobu jak w temacie za pomocą klasy.
Program wygląda mniej więcej tak:
$client = new \Ircykk\AllegroApi\Client($credentials);
$client->authenticate($dbase->getVar("access_token"));
$response = $client->get("/sale/offer-events");

W odpowiedzi dostaję:
stdClass Object
  | (
  | [errors] => Array
  | (
  | [0] => stdClass Object
  | (
  | [code] => NotAcceptableException
  | [message] => Not acceptable representation requested. Please check 'Accept' request header
  | [details] =>
  | [path] =>
  | [userMessage] => The request contains incorrect data. Contact the author of the application.
  | )
  |  
  | )
  |  
  | )

Próba dodania wcześniej:
$headerDefaultsPlugin = new \Http\Client\Common\Plugin\HeaderDefaultsPlugin([
    "Accept-Charset" => "utf-8",
    "Content-Type:" => "application/vnd.allegro.public.v1+json"
]);
$client->addPlugin($headerDefaultsPlugin);

i wielu innych kombinacji nagłówków nic nie dają.

Kiedy testuję wywołania na aplikacji Advanced REST Client i puszczam coś takiego:
GET /sale/offer-events HTTP/1.1
Accept-Charset: utf-8
Authorization: Bearer XXXXXXXXXXX
Content-Type: application/vnd.allegro.public.v1+json

wszystko działa bez najmniejszego problemu, działa nawet coś takiego:

GET /sale/offer-events HTTP/1.1
Authorization: Bearer XXXXXXXXXXX

czyli przekazanie samego tokena bez Content-Type i Charset.

Ja coś robię nie tak, czy gdzieś w klasie jest błąd?
Dzięki za zainteresowanie.

**Comment by ircykk** [comment]
Błąd `NotAcceptableException` zazwyczaj powoduje niewłaściwy `Content-Type` i tutaj [endpoint](https://developer.allegro.pl/documentation/#operation/getOfferEvents) jest w wersji beta więc: `application/vnd.allegro.beta.v1+json`.

Polecam korzystać z klienta w ten sposób: `$client->order()->events()->all(...)`, wtedy klient pilnuje nagłówków.

**Comment by juhacz** [comment]
Dziękuję, tak faktycznie działa. Ale co mam zrobić jeśli chcę pobrać w ten sposób jak próbowałem, czyli przez get? Wiem, że endpoint jest w wersji beta co robiłem źle?

**Comment by ircykk** [comment]
Nagłówek podaj jako drugi argument metody `get` i musi być  `Accept` zamiast `Content-Type`  (nie wiem czemu :) api wymaga ich zamiennie):
```php
$response = $client->get("/sale/offer-events", [
    "Content-Type" => "application/vnd.allegro.beta.v1+json",
    "Accept" => "application/vnd.allegro.beta.v1+json",
]);
```
i ważne bez dwukropka po nazwie, `Content-Type:` jest źle.

**Comment by juhacz** [comment]
Dziękuje, tak działa. Ale w poniższy sposób i tak nie działa :)

```
$headerDefaultsPlugin = new \Http\Client\Common\Plugin\HeaderDefaultsPlugin([
    "Content-Type"=>"application/vnd.allegro.beta.v1+json",
    "Accept"=>"application/vnd.allegro.beta.v1+json"
    ]
);
$client->addPlugin($headerDefaultsPlugin);
```

**Comment by ircykk** [comment]
Nom nie działa w ten sposób, przypuszczam że klient coś miesza w nagłówkach. W wolnej chwili sprawdzę co tam się dzieje.
